parameters:
  miam.colors:
    - "#6a757b"
    - "#f195be"
    - "#f394be"
    - "#7f3e98"
    - "#1b3f95"
    - "#082366"
    - "#009ac6"
    - "#006a5e"
    - "#b76b6d"
    - "#b1c9eb"
    - "#401c00"
    - "#9c600a"
    - "#f2891e"
    - "#e5b539"
    - "#ffe292"
    - "#669044"
    - "#d3e27d"
    - "#d0d3da"
