homepage:
  pattern:  /
  defaults: { _controller: MiamBundle:Sprint:current }

timeline:
  pattern:  /timeline.:_format
  defaults: { _controller: MiamBundle:Timeline:show, _format: html }

story_new:
  pattern:  /story/new
  defaults: { _controller: MiamBundle:Story:new }

story_sort:
  pattern:  /story/sort
  defaults: { _controller: MiamBundle:Story:sort }

story_move:
  pattern:  /story/move
  defaults: { _controller: MiamBundle:Story:move }

story_reestimate:
  pattern:  /story/reestimate
  defaults: { _controller: MiamBundle:Story:reestimate }

story:
  pattern:  /story/:id
  defaults: { _controller: MiamBundle:Story:show }

story_edit:
  pattern:  /story/:id/edit
  defaults: { _controller: MiamBundle:Story:edit }

story_delete:
  pattern:  /story/:id/delete
  defaults: { _controller: MiamBundle:Story:delete }
  requirements: { _method: POST }
  
projects:
  pattern:  /projects
  defaults: { _controller: MiamBundle:Project:index }
  
project_new:
  pattern:  /project/new
  defaults: { _controller: MiamBundle:Project:new }

project:
  pattern:  /project/:id
  defaults: { _controller: MiamBundle:Project:show }
  requirements: { id: "\d+" }

project_sort:
  pattern:  /project/sort
  defaults: { _controller: MiamBundle:Project:sort }

project_edit:
  pattern:  /project/:id/edit
  defaults: { _controller: MiamBundle:Project:edit }

sprint_current:
  pattern:  /
  defaults: { _controller: MiamBundle:Sprint:current }

sprint_ping:
  pattern:  /sprint/ping/:hash
  defaults: { _controller: MiamBundle:Sprint:ping }

sprint_new:
  pattern:  /sprint/new
  defaults: { _controller: MiamBundle:Sprint:new }

sprint_schedule:
  pattern:  /sprint/schedule
  defaults: { _controller: MiamBundle:Sprint:schedule }
  requirements: { _method: POST }
  
fast_login:
  pattern:  /fast-login/:username
  defaults: { _controller: MiamBundle:Miam:fastLogin, username: 'pouet' }
