backlog:
  pattern:  /
  defaults: { _controller: MiamBundle:Story:index }

story_new:
  pattern:  /story/new
  defaults: { _controller: MiamBundle:Story:new }

story_sort:
  pattern:  /story/sort
  defaults: { _controller: MiamBundle:Story:sort }

story:
  pattern:  /story/:id
  defaults: { _controller: MiamBundle:Story:show }

story_edit:
  pattern:  /story/:id/edit
  defaults: { _controller: MiamBundle:Story:edit }