backlog:
  pattern:  /
  defaults: { _controller: MiamBundle:Story:index }

story_new:
  pattern:  /story/new
  defaults: { _controller: MiamBundle:Story:new }

story_sort:
  pattern:  /story/sort
  defaults: { _controller: MiamBundle:Story:sort }

story_move:
  pattern:  /story/move
  defaults: { _controller: MiamBundle:Story:move }

story:
  pattern:  /story/:id
  defaults: { _controller: MiamBundle:Story:show }

story_edit:
  pattern:  /story/:id/edit
  defaults: { _controller: MiamBundle:Story:edit }

story_delete:
  pattern:  /story/:id/delete
  defaults: { _controller: MiamBundle:Story:delete }
  
projects:
  pattern:  /projects
  defaults: { _controller: MiamBundle:Project:index }
  
project_new:
  pattern:  /project/new
  defaults: { _controller: MiamBundle:Project:new }

project:
  pattern:  /project/:id
  defaults: { _controller: MiamBundle:Project:show }

project_edit:
  pattern:  /project/:id/edit
  defaults: { _controller: MiamBundle:Project:edit }

sprint_current:
  pattern:  /sprint
  defaults: { _controller: MiamBundle:Sprint:current }

sprint_new:
  pattern:  /sprint/new
  defaults: { _controller: MiamBundle:Sprint:new }

sprint_schedule:
  pattern:  /sprint/schedule
  defaults: { _controller: MiamBundle:Sprint:schedule }

sprint_addStory:
  pattern:  /sprint/addStory
  defaults: { _controller: MiamBundle:Sprint:addStory }
  
