backlog:
  pattern:  /
  defaults: { _controller: MiamBundle:Miam:index }

story_new:
  pattern:  /story/new
  defaults: { _controller: MiamBundle:Miam:new }

story_sort:
  pattern:  /story/sort
  defaults: { _controller: MiamBundle:Miam:sort }

story:
  pattern:  /story/:id
  defaults: { _controller: MiamBundle:Miam:show }

story_edit:
  pattern:  /story/:id/edit
  defaults: { _controller: MiamBundle:Miam:edit }