imports:
    - { resource: config.yml }

zend.logger:
    priority: debug
    path:     %kernel.logs_dir%/%kernel.environment%.log

doctrine.orm:
    cache_driver:             array           # array, apc, memcache, xcache

web.config:
    toolbar: true
