kernel.config: ~

web.web: ~

web.templating: ~

web.user: ~

# miam.config: ~

markdown.parser: ~

doctrine.dbal:
  default_connection:       default
  connections:
    default:
      event_manager_class:  Doctrine\Common\EventManager
      configuration_class:  Doctrine\DBAL\Configuration
      wrapper_class:        ~
      options:              []

doctrine.orm:
  default_entity_manager:   default
  cache_driver:             apc           # array, apc, memcache, xcache
  entity_managers:
    default:
      connection:           default