kernel.config: ~

web.web: ~

web.templating: ~

web.user: ~

# miam.config: ~

markdown.parser:
  class:                    %markdown.parser.min.class%

markdown.helper: ~

doctrine.dbal:
  default_connection:       default
  connections:
    default:
      event_manager_class:  Doctrine\Common\EventManager
      configuration_class:  Doctrine\DBAL\Configuration
      wrapper_class:        ~
      options:              []

doctrine.orm:
  default_entity_manager:   default
  cache_driver:             apc           # array, apc, memcache, xcache
  entity_managers:
    default:
      connection:           default

parameters:
  miam.user.emails:
    laet:                   laet.wagner@gmail.com
    mbontemps:              matthieu.bontemps@gmail.com
    thib:                   thibault.duplessis@gmail.com
