parameters:
    kernel.include_core_classes: false

kernel.config:
    charset:             UTF-8
    error_handler_level: null

kernel.session:
    lifetime: 2592000 # one month 

web.config:
    validation:
        enabled: true

web.templating:
    escaping:       htmlspecialchars

markdown.parser: ~      # Enable the parser service

auth.config: ~

miam.config: ~

doctrine.orm:
    default_entity_manager:   default
    cache_driver:             apc           # array, apc, memcache, xcache
    entity_managers:
        default:
        connection:           default

parameters:
    miam.user.emails:
        laet:                   laet.wagner@gmail.com
        mbontemps:              matthieu.bontemps@gmail.com
        thib:                   thibault.duplessis@gmail.com
