imports:
    - { resource: config_dev.yml }

zend.logger:
    priority: warn

kernel.test: ~

web.config:
    toolbar: false;

doctrine.dbal:
  connections:
    default:
      driver:               PDOSqlite
      dbname:               miam
      path:                 /tmp/miam.sqlite
