imports:
  - { resource: config.yml }

zend.logger:
  priority: debug
  path:     %kernel.logs_dir%/%kernel.environment%.log

kernel.test: ~

parameters:
  session.options.test.session_path: /tmp/sf2
  
services:
  user.session: @user.session.test

doctrine.orm:
  default_entity_manager:   default
  cache_driver:             array           # array, apc, memcache, xcache
  entity_managers:
    default:
      connection:           default

doctrine.dbal:
  connections:
    default:
      driver:               PDOSqlite
      dbname:               miam
      path:                 /tmp/miam.sqlite
