imports:
  - { resource: config.yml }

zend.logger:
  priority: warn
  path:     %kernel.logs_dir%/%kernel.environment%.log

kernel.test: ~

doctrine.orm:
  default_entity_manager:   default
  cache_driver:             array           # array, apc, memcache, xcache
  entity_managers:
    default:
      connection:           default

doctrine.dbal:
  connections:
    default:
      driver:               PDOSqlite
      dbname:               miam
      path:                 /tmp/miam.sqlite
