imports:
  - { resource: config.yml }

parameters:
  user.session.class: Symfony\Framework\WebBundle\Session\ArraySession

zend.logger:
  priority: debug
  path:     %kernel.logs_dir%/%kernel.environment%.log

kernel.test: ~
