imports:
  - { resource: config.yml }

zend.logger:
  priority: debug
  path:     %kernel.logs_dir%/%kernel.environment%.log

kernel.test: ~

parameters:
  session.options.test.session_path: /tmp/sf2
  
services:
  user.session: @user.session.test
